// ============================================================
// Customer Signup Form - SIMPLE 4-FIELD registration
// ============================================================
// Requires: First Name, Email, NIC, Phone Number.
// Password is auto-generated so registration is fast.
// User completes their full profile after login.
// ============================================================

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../providers/auth_provider.dart';
import '../../../features/home/screens/home_screen.dart';

class CustomerSignupForm extends StatefulWidget {
  const CustomerSignupForm({super.key});
  @override
  State<CustomerSignupForm> createState() => _CustomerSignupFormState();
}

class _CustomerSignupFormState extends State<CustomerSignupForm> {
  final _formKey = GlobalKey<FormState>();
  final _fName = TextEditingController();
  final _email = TextEditingController();
  final _nic = TextEditingController();
  final _phone = TextEditingController();

  @override
  void dispose() {
    _fName.dispose();
    _email.dispose();
    _nic.dispose();
    _phone.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;
    final auth = context.read<AuthProvider>();

    // Send the essential fields — password auto-generated by backend
    final data = {
      'role': 'CUSTOMER',
      'firstName': _fName.text.trim(),
      'email': _email.text.trim(),
      'nic': _nic.text.trim(),
      'phone': _phone.text.trim(),
    };

    final success = await auth.signup(data);
    if (!mounted) return;
    if (success) {
      // Profile is incomplete — user will be prompted to complete after login
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            'Account created! Please complete your profile to start hiring drivers.',
          ),
          backgroundColor: Colors.indigo,
          duration: const Duration(seconds: 4),
        ),
      );
      Navigator.pushReplacement(
        context,
        MaterialPageRoute(builder: (_) => const HomeScreen()),
      );
    } else {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(auth.error ?? 'Registration failed')),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Form(
      key: _formKey,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          // Info card explaining quick registration
          Container(
            padding: const EdgeInsets.all(12),
            margin: const EdgeInsets.only(bottom: 16),
            decoration: BoxDecoration(
              color: Colors.indigo.shade50,
              borderRadius: BorderRadius.circular(10),
              border: Border.all(color: Colors.indigo.shade200),
            ),
            child: const Row(
              children: [
                Icon(Icons.info_outline, color: Colors.indigo, size: 20),
                SizedBox(width: 8),
                Expanded(
                  child: Text(
                    'Quick signup in under a minute! You can complete your full profile after logging in.',
                    style: TextStyle(fontSize: 12, color: Colors.indigo),
                  ),
                ),
              ],
            ),
          ),

          // First Name
          Padding(
            padding: const EdgeInsets.only(bottom: 12),
            child: TextFormField(
              controller: _fName,
              textCapitalization: TextCapitalization.words,
              decoration: const InputDecoration(
                labelText: 'First Name *',
                prefixIcon: Icon(Icons.person),
                border: OutlineInputBorder(),
              ),
              validator: (v) =>
                  (v == null || v.isEmpty) ? 'First name is required' : null,
            ),
          ),

          // Email
          Padding(
            padding: const EdgeInsets.only(bottom: 12),
            child: TextFormField(
              controller: _email,
              keyboardType: TextInputType.emailAddress,
              decoration: const InputDecoration(
                labelText: 'Email Address *',
                prefixIcon: Icon(Icons.email_outlined),
                border: OutlineInputBorder(),
              ),
              validator: (v) {
                if (v == null || v.isEmpty) return 'Email is required';
                if (!v.contains('@') || !v.contains('.')) return 'Enter a valid email';
                return null;
              },
            ),
          ),

          // NIC
          Padding(
            padding: const EdgeInsets.only(bottom: 12),
            child: TextFormField(
              controller: _nic,
              textCapitalization: TextCapitalization.characters,
              decoration: const InputDecoration(
                labelText: 'NIC Number *',
                prefixIcon: Icon(Icons.badge_outlined),
                border: OutlineInputBorder(),
              ),
              validator: (v) =>
                  (v == null || v.isEmpty) ? 'NIC is required' : null,
            ),
          ),

          // Phone
          Padding(
            padding: const EdgeInsets.only(bottom: 24),
            child: TextFormField(
              controller: _phone,
              keyboardType: TextInputType.phone,
              decoration: const InputDecoration(
                labelText: 'Phone Number *',
                prefixIcon: Icon(Icons.phone),
                border: OutlineInputBorder(),
              ),
              validator: (v) =>
                  (v == null || v.isEmpty) ? 'Phone number is required' : null,
            ),
          ),

          // Register button
          ElevatedButton.icon(
            onPressed: _submit,
            style: ElevatedButton.styleFrom(
              padding: const EdgeInsets.symmetric(vertical: 14),
              backgroundColor: Colors.indigo,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(10),
              ),
            ),
            icon: const Icon(Icons.person_add, color: Colors.white),
            label: const Text(
              'Register as Customer',
              style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold),
            ),
          ),
        ],
      ),
    );
  }
}